"""Plan only real account entrants and assess actual supplied paired outcomes.

No zero-treatment account worker is started. Candidate wallets cannot be
generated by multiplying original curves. This is finite research admission.
"""
import argparse
import gzip
import json
from pathlib import Path
import time

from research import nine_routes as r, loop_data as data, loop_alpha as alpha, loop_risk as risk
from research.nine_joint import quarter


def entrants(value,path='routes'):
    if isinstance(value,dict):
        if value.get('account_entrant') is True:
            yield path,value
        else:
            for key,row in value.items():yield from entrants(row,path+':'+key)
    elif isinstance(value,list):
        for i,row in enumerate(value):yield from entrants(row,path+':'+str(i))


def plan(screen,starts):
    if screen['spec_sha256']!=r.sha(data.SPEC.read_bytes()):raise ValueError('foreign screen contract')
    jobs=[];pending=[];seen=set()
    for path,item in entrants(screen['routes']):
        identity=(item.get('kind'),item.get('family',path),item.get('expression'))
        if identity in seen:continue
        seen.add(identity)
        events=item.get('selected_events',item.get('events',item.get('rows',[])))
        hits=[e for e in events if e.get('signal',e.get('selected',float(e.get('factor',1))<1)) is True]
        selected=[]
        for early in (True,False):
            eligible=[e['at_ms'] for e in hits if (e['at_ms']<1640995200000)==early]
            if not eligible:continue
            begin,end=quarter(min(eligible));subset=[t for t in starts if begin<=t<end]
            if end>1789862400000 or not subset or len(subset)>40:continue
            selected.append(dict(window=[begin,end],starts_ms=subset,eligible_at_ms=min(eligible)))
        if len(selected)!=2:
            pending.append(dict(route=path,status='WAIT_TWO_ORIGINAL_ERA_WINDOWS',meaning='No new start/date extension to manufacture effect.'));continue
        jobs.append(dict(route=path,kind=item.get('kind'),family=item.get('family'),expression=item.get('expression'),
            windows=selected,required_accounts=['baseline','uniform25','candidate'],
            status='REQUIRE_ACTUAL_SOURCE_BOUND_ACCOUNTS'))
    # Two windows, three scenarios, two independent wallets per admitted job.
    if len(jobs)*12>24:raise ValueError('registered24-account budget exceeded; preregister selection before account production')
    return dict(status='ACCOUNT_COMPARISON_REQUIRED' if jobs else 'NO_ACCOUNT_ENTRANT',jobs=jobs,pending=pending,
        planned_max_new_accounts=len(jobs)*12,new_accounts=0,new_sessions=0,original795_replays=0,
        selection='Earliest actual qualified event per original era; no observed return selection.',
        default_adopted=False,orders=0)


def assess(cases):
    """Use actual audit/commitments/risk gates; no manually supplied PASS flag."""
    if set(cases)!={'baseline','uniform25','candidate'}:raise ValueError('all independent controls required')
    compact={}
    base=cases['baseline']['raw']
    def commitments(raw):
        return {(kind,t['time'],str(t.get('order_id',t.get('orderId')))):str(t['qty'])
            for kind,a in raw['accounts'].items() for t in a['fills' if kind=='spot' else 'trades']
            if t.get('buyer',t.get('side')=='BUY')}
    original=commitments(base)
    for name,case in cases.items():
        raw=case['raw'];alpha.verify_account_packet(raw,int(time.time()*1000))
        curve=[]
        for row in raw['curve']:
            if not raw['window'][0]<=row['at_ms']<=raw['window'][1]:raise ValueError('out-of-window joint valuation')
            if curve and curve[-1]['at_ms']==row['at_ms']:curve[-1]=row
            else:curve.append(row)
        changed=sum(commitments(raw).get(key)!=original.get(key) for key in set(commitments(raw))|set(original))
        compact[name]=dict(finished=raw['finished'],final_cny=raw['final_cny'],
            synchronized_observed_mdd=risk.drawdown(curve)['mdd'],changed_commitments=changed)
    for case in cases.values():
        if case['raw']['window']!=base['window']:raise ValueError('paired windows differ')
    gates=r.pair_gate(compact['candidate'],compact['baseline'],compact['uniform25'])
    return dict(status='WINDOW_PASS' if all(gates[k] for k in ('audits','actual_action','risk_wealth','beats_simple')) else 'WINDOW_REJECT',
        gates=gates,default_adopted=False,meaning='Finite historical research window; never full-window/native adoption.')


def main(argv=None):
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--screen',type=Path,required=True);p.add_argument('--schedule',type=Path,required=True)
    p.add_argument('--out',type=Path,required=True);p.add_argument('--account-manifest',type=Path);args=p.parse_args(argv)
    raw=args.screen.read_bytes();screen=json.loads(raw);starts=json.loads(args.schedule.read_text())['primary']['starts_ms']
    spec=json.loads(data.SPEC.read_text())
    if r.sha(json.dumps(starts,separators=(',',':')).encode())!=spec['contract']['schedule_sha256']:raise ValueError('original starts changed')
    result=plan(screen,starts)
    if args.account_manifest:
        if not result['jobs']:raise ValueError('no screen entrant; do not manufacture a comparison')
        manifest_raw=args.account_manifest.read_bytes();manifest=json.loads(manifest_raw);results=[]
        if manifest['screen_sha256']!=r.sha(raw) or manifest['spec_sha256']!=screen['spec_sha256']:raise ValueError('account source contract changed')
        for window in manifest['windows']:
            jobs=[j for j in result['jobs'] if j['route']==window['route']]
            if len(jobs)!=1 or window['window'] not in [w['window'] for w in jobs[0]['windows']]:raise ValueError('unregistered account window')
            cases={}
            for name,item in window['cases'].items():
                original=(args.account_manifest.parent/item['file']).read_bytes()
                if r.sha(original)!=item['sha256']:raise ValueError('actual account bytes changed')
                cases[name]=dict(raw=json.loads(gzip.decompress(original)),binding=item)
            if any(c['raw']['window']!=window['window'] for c in cases.values()):raise ValueError('mislabelled account window')
            results.append(dict(route=window['route'],window=window['window'],evaluation=assess(cases),
                original_sources={name:{k:a['source'] for k,a in c['raw']['accounts'].items()} for name,c in cases.items()}))
        expected={(j['route'],tuple(w['window'])) for j in result['jobs'] for w in j['windows']}
        actual=[(w['route'],tuple(w['window'])) for w in results]
        if set(actual)!=expected or len(actual)!=len(expected):raise ValueError('missing or duplicate preregistered account comparison')
        result.update(actual_window_evaluations=results,account_manifest_sha256=r.sha(manifest_raw),
            status='FINITE_ACCOUNTS_PASS' if all(w['evaluation']['status']=='WINDOW_PASS' for w in results) else 'FINITE_ACCOUNTS_REJECT')
    result.update(format='btc-loop-account-admission-v1',source=data.source(),screen_sha256=r.sha(raw),spec_sha256=screen['spec_sha256'])
    data.new_json(args.out,result);print(json.dumps(dict(status=result['status'],jobs=len(result['jobs']),new_accounts=0)))


if __name__=='__main__':main()
