"""Seal completed independent calculations; no financial/account recalculation."""
from recompute import *
from collections import Counter
phase=load(OUT/'category-phase-complete.json');accounts_phase=load(OUT/'account-phase-complete.json');a={k:load(p) for k,p in accounts_phase['account_paths'].items()};j=load(OUT/'journal-sizing-supplement.json');prov=load(OUT/'provenance-supplement.json');sources=load(OUT/'original-source-archive-binding.json');canonical=load(OUT/'spot-canonical-five-case-proof.json');portfolios=load(OUT/'independent-portfolio-statistics.json')
require(len(a)==len(j['accounts'])==71 and j['passed'] and prov['passed'] and sources['passed'] and len(canonical['cases'])==5,'all financial stages complete')
proof={'format':'btc-edge-financial-review-v1','preliminary':phase['preliminary'],'inventory_sha256':phase['inventory_sha256'],'reviewer_source':phase['reviewer_source'],'checks':phase['checks']}
proof_path=WORK/'assessment/independent-financial-review-proof.json';put(proof_path,proof)
sys.path.insert(0,str(ROOT/'spotquant'));from research.edge_assessment import verify_financial_review
validated=verify_financial_review(proof_path,R);put(OUT/'serialized-proof-verification.json',{'passed':True,'verification':validated,'account_calculations_repeated':0});print('FINAL FINANCIAL PROOF PASS',sha(proof_path),flush=True)
# No-change Coin bridge draws from current actual source plus independently closed five baseline comparisons.
coinid=ident('perp','incumbent');coin=a[coinid];ci={x['id']:x for x in load(OUT/'baseline_six_groups.json')['recomputations'] if x['id'].startswith('perp:')}
coinproof={'format':'btc-edge-incumbent-independent-financial-bridge-v1','status':'independently_reviewed','source':sources['projects']['coinquant']['source'],'measured_source':coin['source'],'native_runtime_files':prov['coin_native_runtime_files'],'five_cases':ci,'source_archive':sources['projects']['coinquant']['archive'],'native_cases':0,'actual_account_days':0,'prospective_alpha_proven':False};put(OUT/'coin-incumbent-case-proof.json',coinproof)
coin_template={'candidate':'incumbent','adapter':'canonical-incumbent-v1','components':[],'scale':'1','source':coinproof['source'],'measured_source':coin['source'],'account_id':coinid,'raw_sha256':coin['raw_sha256'],'original_accepted_result_sha256':sorted({a[ident('perp','incumbent',s)]['raw_sha256'] for s in STRESS['perp']}|{a[ident('perp','incumbent',risk=True)]['raw_sha256']}),'canonical_review_sha256':sha(OUT/'coin-incumbent-case-proof.json')};put(OUT/'coin-incumbent-bridge-template.json',coin_template)
counts=Counter()
for v in j['accounts'].values():counts.update(v['counts'])
artifacts={str(p):sha(p) for p in sorted(OUT.rglob('*')) if p.is_file() and '__pycache__' not in str(p) and p.suffix in ['.py','.json','.log'] and p.name!='acceptance.log'}
full={'format':'btc-edge-full-independent-financial-review-v1','status':'PASS','financial_proof':{'path':str(proof_path),'sha256':sha(proof_path)},'preliminary':phase['preliminary'],'inventory_sha256':phase['inventory_sha256'],'complete_accounts':71,'spot_accounts':46,'coin_accounts':25,'original_raw_files':53,'canonical_complete_accounts':5,'category_counts':{k:len(load(v['artifact']['path'])['recomputations']) for k,v in phase['checks'].items()},'artifacts':artifacts,'independent_journal_event_count':sum(v['events_scanned'] for v in j['accounts'].values()),'journal_counts':dict(counts),'pending':[],'blocking':[],'financial_source_mismatches':[],'native_cases':0,'actual_account_days':0,'prospective_alpha_proven':False,'targets':{'spot':'NOT_MET','perp':'NOT_MET'},'native_qualification':'NOT_QUALIFIED'};put(OUT/'financial-proof.json',full)
lines=['# Independent final financial review','', '**Financial PASS.** All 71 registered accounts and the separate five canonical Spot cases reconcile. No accounting, source, input, original-evidence, or adoption-gate mismatch remains. This accepts the evidence and registered selection; it does not meet the original economic targets or qualify native execution.','',f"Machine proof: `{proof_path}` SHA256 `{sha(proof_path)}`.",f"Full independent evidence index: `financial-proof.json` SHA256 `{sha(OUT/'financial-proof.json')}`.",'',f"Preliminary SHA256 `{sha(PRE)}`; inventory `{phase['inventory_sha256']}`. Exactly 46 Spot + 25 Coin accounts in 53 original raw files; pending/blocking/rejected lists are empty. The additional five canonical cases are separate source-bridge measurements.",'','## Independence and coverage','', 'The standalone recompute.py reads original fills, commissions, funding/income, signed quantities, average-cost entry, daily wallet records, official market ZIPs, and prior-day FX. It independently reconstructs every closing wallet and daily equity observation, checks no external flows, and derives all report metrics, including daily/validation returns, beta, HAC7 intercept covariance, capture, calendar attribution, ES99, underwater duration and producer-specific CAGR. Original snapshots are admitted to curve encoding only after ledger reconstruction; sub-1e-8 original Decimal-ledger rounding follows the frozen monetary convention. Acceptance gates use exact original finite Decimal MDD strings, without float conversion/tolerance. Continuous MDD is the original producer’s OHLC/minute-envelope proxy, bound to all original fields; no independent continuous second-engine replay is claimed.','', 'categories.py derives profiles, achieved risk, every adoption threshold/ranking, and all six actual independently funded portfolio sums. Only after derivation does it import review_expectations/verify_review_value to compare exact typed records; it never generates evidence by dumping expected values. The serialized final proof was verified once; financial calculations were not replayed. All complete accounts have 2,454 UTC daily closes and all registered 795 sessions, except Spot outage’s 789. Every session and write clock was checked. Sampling additionally retains first/last/every97th session and all exceptional/unknown/constraint/reason cases; journals retain every exceptional feature/sizing event plus deterministic periodic ownership records.','',f"Independent categories: {full['category_counts']}. Journal events scanned: {full['independent_journal_event_count']:,}; Coin decision scales: {counts['decision_scale']:,}; unchanged Coin committed/topup targets: {counts['held_target_unchanged']:,}; pre-cutoff daily identities: {counts['training_daily_identity']:,}. Reused scoped software/controller/forward reviews remain distinct from this financial evidence.",'','## Sources and provenance','']
for kind,name in [('spot','spotquant'),('perp','coinquant')]:
 s=sources['projects'][name];lines.append(f"- {kind}: original HEAD `{s['source']['git_head']}`, full Python `{s['source']['python_sources_sha256']}`; {s['protected_count']} protected archived files/modes independently match original/current execution bytes. Archive `{s['archive']['path']}` SHA `{s['archive']['sha256']}`.")
lines += ['', 'Metadata-only dirty PROJECT_STATE/HANDOFF files do not relabel financial source. Both own edge spec/protocol contracts, original meter/source identities, schedule, FX, feature inputs, profile bytes, fixed budgets and offsets remain bound. Original Coin’s 20 native runtime files match accepted incumbent bytes; its forward reader remains standalone. No source/default promotion occurred in this review.','',f"The provenance supplement binds {len(prov['bound_file_sha256']):,} actual files and 11 controller phase receipts, including both original failed phases and all durable releases. Initial SQLITE_FULL output/exit evidence remains failed and retained. Exactly one pre-outcome resource recovery switched task TMPDIR to overlay storage and cap1/project, with UID/HOME and locks unchanged. First preparation/helper hashes are historical: later separately reviewed fixes are bound by the actual freeze; preserved pre-controller-fix1 files match the old preparation hashes. No controller tests were repeated.",'', 'The first post-risk assessment failed only because the -60s original account consumed the additional 2026-08-01 official aggTrades archive. The raw account was preserved. The assessment-only union retains 1,596 original read-only hardlinks plus the exact original consumed ZIP/CHECKSUM pair, retrieved HTTP200 from official URLs and matching its older raw receipt. ZIP SHA `6bfdb219726ab774c25ae782e4e8f4a5e4dbc69b807f1b7c200e71586d69b6fb`; CHECKSUM `1283c92250f64ee7db709a8e1952f682fad1ec3131e9ec6d9690aaa52a6ecec0`. Correction report SHA `9445a934a22a36e5803544259aa900debdd97e03a2da5318ebaef804c1a8b162`. Final evaluation must use the same union path. This restored verification input, not prices, source or financial accounts.','', 'All approved first-failure reviews and scoped corrections remain retained, including source archive mode verification, controller C1–C4/resource-recovery, canonical malformed payload R1, and the single corrected partial-entry fixture. This review ran no producers, unit/fullsuite tests, network requests, native/account/private actions, public preflights, initialization or export.','', '## Actual economics and selection','', '| Project / base account | CNY CAGR | Original continuous proxy MDD | Worst CNY day | ES99 loss | Underwater days | Fees USDT | Funding paid USDT |','|---|---:|---:|---:|---:|---:|---:|---:|']
for kind,n in [('spot','atr-stop'),('spot','crowding-interaction'),('perp','incumbent')]:
 x=a[ident(kind,n)];v=x['gate_inputs']['values'];m=x['metrics'];lines.append(f"| {kind} {n} | {v['cagr']:.6%} | {D(v['mdd']):.6%} | {v['worst_day']:.6%} | {v['es99']:.6%} | {v['underwater']} | {D(m['fees_usdt']):.6f} | {D(m['funding_paid_usdt']):.6f} |")
lines += ['', '| Candidate | Eligible | Rejected gates | Validation beta / vol | Validation cumulative USDT return gain |','|---|---|---|---|---:|']
for kind,decisions in R['decisions'].items():
 for n,d in decisions.items():
  s=d['achieved_risk']['candidate'];lines.append(f"| {kind} {n} | {d['eligible']} | {', '.join(d['reasons']) or 'none'} | {s['beta']:.6f} / {s['volatility']:.6%} | {d['achieved_risk']['validation_total_usdt_return_gain']:.6f} |")
lines += ['', 'Training independently uses exactly 731 2020–2021 USDT observations, slicing before statistics. Spot scales are ATR1, exit-confirm0.914338712559913, stop-budget1, crowding1; Coin’s four profiles are1. The raw base hashes and own-project schema match actual consumed profile bytes. Risk changes only new order sizing from 2022-01-01; held targets remain unchanged and no curve is multiplied. Scale0 is permitted by the frozen finite guards; it was not a fitted actual scale and no optional boundary test was run. The 1.05 volatility/+0.02 beta conditions are upper bands, not risk equality. Both Coin quality-budget and cost-horizon fail actual risk bands despite positive validation gain.','', 'Selection is Spot crowding-interaction and Coin incumbent. Only Spot crowding passes all gates; no ALL-components combination is applicable. The pre-outcome selection ruling ranks eligible singles by worst-stress CAGR/registered order, then a complete eligible ALL-components combination may supersede the best single even with lower worst-stress CAGR. No global single-plus-combination maximum is claimed. All losing cases remain legitimate completed financial results.','', '**Material interpretation limit:** Across registered Spot decision journals, 689 crowding proposals retained the original quote and 200 were blocked for missing causal features; no triple-condition halving event occurred. The observed historical gain therefore comes from unavailable-input entry blocking on these measured paths and does not establish profitability of the halving branch. The reviewed shared predicate and five measured source comparisons establish implementation/equivalence; synthetic branch tests are separately retained. Missing features affect new BUY only; exits/protection are preserved by the reviewed code and bridge.','', '| Selected base account | Full-window BTC beta | Annualized residual intercept | HAC7 descriptive normal95 interval | Up / down arithmetic capture |','|---|---:|---:|---|---|']
for kind,n in [('spot','crowding-interaction'),('perp','incumbent')]:
 m=a[ident(kind,n)]['metrics'];g=m['usdt_btc_regression'];cap=m['btc_up_down_day_capture'];ci=g['residual_arithmetic_annualized_normal95_descriptive'];lines.append(f"| {kind} {n} | {g['beta_btc']:.6f} | {g['residual_arithmetic_annualized']:.6%} | [{ci[0]:.6%}, {ci[1]:.6%}] | {cap['up']['arithmetic_capture_ratio']:.6f} / {cap['down']['arithmetic_capture_ratio']:.6f} |")
lines += ['', 'These intercepts and intervals are descriptive and selection-contaminated. They do not establish clean out-of-sample or prospective alpha. The validation-period results and full-window results are separately retained in every independent account checkpoint.','', '## Actual two-account budgets','', '| Selection | Spot/Coin CNY | Daily CAGR | Daily joint MDD | Worst CNY day | BTC beta | Return correlation |','|---|---|---:|---:|---:|---:|---:|']
for label,ps in portfolios.items():
 for x in ps:lines.append(f"| {label} | {'/'.join(map(str,x['budgets']))} | {x['daily_cny']['cagr']:.6%} | {x['daily_cny']['daily_mdd']:.6%} | {x['daily_cny']['worst_day']:.6%} | {x['regression']['beta_btc']:.6f} | {x['correlation']:.6f} |")
lines += ['', 'Each row sums two genuine separately funded accounts with CNY10000 total, zero transfers/additions/rebalancing, and its own fees, minimum notionals, rounding and realized paths. Selected Spot’s additional three accounts were conditionally registered with 54 exact bindings and actually completed. 5000/5000 is the fixed neutral reference. The other splits are robustness evidence, not allocation recommendations or a selected historical optimum. Daily joint MDD is not independent continuous joint MDD.','', '## Separate canonical acceptance and remaining binding','',f"All five canonical Spot cases (base, fee150, slip2, outage, unity-risk-base) independently reconcile in financial/fills/daily/ownership/operating/remaining_original_fields groups. Case proof SHA `{sha(OUT/'spot-canonical-five-case-proof.json')}`. New source is HEAD `609606d9c0e0ad8d3c3038b329c9c4ab6d1b9629` / Python `b81f1bfee086e875cbf8ff22a67b2cfdff419130a7918a6ce8754b2e9e2936c5`, distinct from original74bd/Pythonf2d6. The five-account template preserves both identities and command receipts. See spot-canonical-five-financial-review.md and spot-canonical-bridge-template.json; Coin’s unchanged runtime proof/template is separate.",'', 'Final report bytes and later metadata/current-source HEAD are not yet available. The same reviewer may bind those final identities to these already-completed calculations and protected byte maps, without rerunning the 71 or five cases. This report itself authorizes no source edits, native execution, export or initialization.','', '## Preserved review-calculation corrections','', 'The first account script rejected legitimate resting protective allocations, then a null flat sleeve; each initial script/log remains and only incomplete portions resumed, reusing all completed checkpoints. The first canonical attempt used an incorrect archive subdirectory before any case calculation; the path was corrected to the actual bound archive. Supplement failures retained a null suffix-filter handling error and a historical preparation path mismatch; the latter was resolved to preserved pre-fix helper bytes, not by relaxing source hashes. These were review-script assumptions, not producer/account mismatches. Passing account/canonical calculations and six categories were not rerun.','', 'Both original targets remain **NOT_MET**: Spot56.598116% CAGR/36.412249% proxy MDD falls short of100%/30%; Coin119.228356% CAGR falls short of150% (44.105079% proxy MDD remains below50%). Native cases0, actual account-days0, prospective_alpha_proven=false, native qualification **NOT_QUALIFIED**. Continuous OHLC and minute-envelope paths, 29 missing official mark minutes, prior-day FX/USD-par conventions, missing-feature assumptions, confirmed-stop replacement gaps and unresolved native protection remain disclosed.','']
with (OUT/'financial-review.md').open('x') as f:f.write('\n'.join(lines))
cl=['# Independent five-canonical Spot financial review','', '**PASS for exact historical financial/source equivalence.** All five complete canonical accounts were independently reconstructed and compared with their exact original selected-research counterparts in all six established groups. This is not a native execution or profitability qualification.','',f"Canonical inventory `{WORK/'canonical-spot/canonical-inventory.json'}` SHA `1d4dd97eb7d9941073f1413f82f885f0baefd024f37f61377f12c1b39ba75eb3`.",f"Case proof `spot-canonical-five-case-proof.json` SHA `{sha(OUT/'spot-canonical-five-case-proof.json')}`.",f"Template `spot-canonical-bridge-template.json` SHA `{sha(OUT/'spot-canonical-bridge-template.json')}`.",'', '| Case | Original raw SHA256 | Canonical raw SHA256 | Actual finish receipt SHA256 |','|---|---|---|---|']
for label,d in canonical['cases'].items():
 c=d['bridge_case'];cl.append(f"| {label} | {c['original_raw_sha256']} | {c['canonical_raw_sha256']} | {c['command_receipt_sha256']} |")
cl+=['','Original measured source remains74bd6e035e36531c517029077c1a9e2e5ec44516/Pythonf2d6c3e73c2acb7b328a7a0e2678bb95ceb77d8a17a46139abfe8b357befdbf6. Canonical source is609606d9c0e0ad8d3c3038b329c9c4ab6d1b9629/Pythonb81f1bfee086e875cbf8ff22a67b2cfdff419130a7918a6ce8754b2e9e2936c5, protected archive `250bd1381114afde1b06d835185b908b1b499d3c773d53bf4ac6baecf580175a`, 58 files/modes. Metadata equality never substitutes for these separate original/native execution byte identities.','', 'Each case separately reconstructs fills, BTC/USDT fees, terminal cash/BTC/FX equity, every daily observation, all attribution/tail metrics and every write/session clock. Each independently derived six-group hash exactly matches its original selected research raw. Only the pre-approved relational client-ID spelling and independently verified archive-hash normalization and named new instrumentation exclusions apply. Candidate/scenario/risk/subpool annotations are checked separately; original and canonical research_identity objects remain retained verbatim and differ intentionally by actual execution/source. No original raw field is rewritten.','', 'The four normal cases complete795 sessions; outage789. Every archive and original audit passes. The fifth uses the exact original unity calibration bytes. Existing ATR, free-pool90%, minimum/rounding, held ownership, native stop/cleanup and safety behavior remain on the separately reviewed shared execution path. The scoped canonical review and required affected-check receipts are reused; no software checks or financial accounts were rerun.','', 'No actual triple-condition halve occurs in registered historical Spot journals; observed differences come from missing causal-feature entry blocks. The shared predicate nevertheless requires funding>.0003 AND previous completed UTC basis>.01 AND current completed close<=five-completed-days-prior close, halving NEW BUY once. Missing required inputs block NEW only. The reviewed code/branch tests establish this rule; historical returns do not validate the unobserved branch’s profitability.','', 'The template already contains all fields required by verify_spot_bridge. Final current-source/export/report identities are intentionally not fabricated. A later same-reviewer final-binding follow-up must verify protected-byte equivalence and bind final metadata/report/bridge artifacts, reusing these five case calculations. Native cases0; actual account-days0; prospective alpha false; original targets NOT_MET; qualification NOT_QUALIFIED.','']
with (OUT/'spot-canonical-five-financial-review.md').open('x') as f:f.write('\n'.join(cl))
put(OUT/'delivery-artifacts.json',{'financial_review':{'path':str(OUT/'financial-review.md'),'sha256':sha(OUT/'financial-review.md')},'financial_proof':{'path':str(proof_path),'sha256':sha(proof_path)},'evidence_index':{'path':str(OUT/'financial-proof.json'),'sha256':sha(OUT/'financial-proof.json')},'canonical_review':{'path':str(OUT/'spot-canonical-five-financial-review.md'),'sha256':sha(OUT/'spot-canonical-five-financial-review.md')},'canonical_proof':{'path':str(OUT/'spot-canonical-five-case-proof.json'),'sha256':sha(OUT/'spot-canonical-five-case-proof.json')},'spot_template':{'path':str(OUT/'spot-canonical-bridge-template.json'),'sha256':sha(OUT/'spot-canonical-bridge-template.json')},'coin_proof':{'path':str(OUT/'coin-incumbent-case-proof.json'),'sha256':sha(OUT/'coin-incumbent-case-proof.json')},'coin_template':{'path':str(OUT/'coin-incumbent-bridge-template.json'),'sha256':sha(OUT/'coin-incumbent-bridge-template.json')},'final_binding_pending_only':True,'status':'PASS'})
print('DELIVERY',json.dumps(load(OUT/'delivery-artifacts.json')),flush=True)
