import json
from pathlib import Path

shared = {
 'format': 'btc-alpha-beta-edge-spec-v1', 'registration': '2026-10-03-before-new-financial-outcomes',
 'symbol': 'BTCUSDT', 'initial_cny': '10000', 'added_cash': '0',
 'window': {'start_inclusive': '2020-01-01T00:00:00Z', 'end_exclusive': '2026-09-20T00:00:00Z', 'start_ms': 1577836800000, 'end_ms': 1789862400000},
 'execution': {'frozen_original_starts': 795, 'session_seconds': 300, 'poll_seconds': 5, 'stopped_client_actions': False, 'retain_original': ['FX/conversion', 'costs', 'latency', 'actual fills/funding', 'protection', 'ownership', 'capital ceilings', 'durable recovery'], 'native_qualification': 'NOT_QUALIFIED', 'actual_account_days': 0},
 'features': {'format': 'edge-features-v1', 'raw_sha256': '1d87be0b4c8cd8a7eacd4970a1a194e5f1ed0b2f3aa3710a43417aa9ab066ef2', 'raw_counts': {'funding':7488,'basis':2485}, 'funding': {'observation':'actual settlement timestamp, preserve jitter and negative rates', 'available_lag_ms':28800000, 'stale_age_gte_ms':28800000, 'predicted_or_future_cashflow':False}, 'basis': {'observation':'previous matched UTC-day completion boundary = raw available_ms - 60000', 'available_lag_ms':60000, 'max_age_ms':86400000, 'require_current_utc_availability_date':True, 'publication':'modeled assumption, not measured', 'meaning':'daily futures trade-close / spot trade-close - 1; not executable instantaneous basis'}, 'missing':'None with explicit cause; never zero fill', 'historical_lookup':'frozen window only; retained raw future tail cannot extend it', 'forward':'separate newly collected observations, no retrospective backfill', 'trend':'completed bars only, causal current/history checkpoints; no future bars'},
 'controls': {'cash':'same finite account/session/Lifecycle gates', 'protected_participation':[{'name':f'protected-participation-{n}','fraction':str(n/100),'installed_protective_stop_fraction':'.28'} for n in [25,50,75,100]], 'entry':'genuine cold-start gates, no held topups or rebalances; re-entry only next completed UTC day after actual stop', 'disclosure':'different signal/protection rules; actual protected funded accounts, not pure buy-and-hold or fixed constant weights; no fractional daily-open execution curves'},
 'baseline_equality': {'groups': ['financial','fills','daily','ownership','remaining','operating'], 'rule':'accepted six evidence groups under existing allowed normalization; unexplained mismatch blocks promotion'},
 'risk_calibration': {'per_project_document':True, 'profiles':'keyed by own project candidate; bind project kind and baseline, input/spec/source identities', 'training':'2020-2021 USDT, exactly 731 days; no validation fitting', 'cutoff_ms':1640995200000, 'scale_before_cutoff':'1', 'scale_formula':'max(.01, min(1, baseline_train_vol/candidate_train_vol, baseline_positive_beta/candidate_positive_beta when candidate beta exceeds baseline))', 'effect':'actual new order sizing after cutoff only; no held retroactive shrink or curve scaling', 'actual_base_reruns':'baseline scale1 and each registered candidate', 'validation_vol_upper_multiple':'1.05', 'validation_beta_upper_additive':'.02', 'disclosure':'upper bands, not exact risk equality; history contaminated; intercept and CI descriptive'},
 'adoption': {'complete_known_audited_original_matched_stresses':True, 'each_scenario_cagr_min':'baseline - .01', 'base_improvement':'CAGR >= baseline + .01 OR (continuous MDD <= baseline - .01 AND CAGR >= baseline - .01)', 'base_worst_cny_day_min':'baseline - .005', 'historical_es99_loss_max_multiple':'1.05', 'longest_underwater_max':'baseline', 'return_increasing':'both actual risk upper bands AND validation cumulative USDT return gain > 0', 'risk_only_alternative':'both actual risk upper bands AND continuous MDD reduction >= .01 AND validation gain >= -.01', 'ranking':'highest worst-stress CAGR, then registered candidate order', 'combination':'all individually eligible compatible mechanisms, no subset search; all four stresses and actual calibrated base; adopt only own gates pass', 'annualization':'each original producer year convention, explicitly retained', 'targets':'NOT_MET unless exact original goals pass; selection is separate from targets'},
 'portfolio': {'fixed_cny_pairs_spot_coin': [[2500,7500],[5000,5000],[7500,2500]], 'neutral_reference':[5000,5000], 'accounts':'actual fixed funded account pairs for current default, and final selected if different', 'cash_flow':'no additions/transfers/rebalance', 'aggregation':'sum actual synchronized daily equity and closing BTC exposure', 'mdd':'daily joint MDD is not continuous joint MDD', 'other_splits':'sensitivity evidence, no optimized default'},
 'research_constraints': {'parameter_search':False,'subset_search':False,'start_offset_selection':False,'prior_simple_filters':'funding OR basis filters failed prior research; not registered new hypotheses', 'phase_fix':'none; Task1 establishes different observed marks at earliest divergence, no precise unnecessary same-observation dependency', 'source_freeze':'clean committed producers/evaluator and exact spec/input identities before financial measurements; originals immutable'},
 'inventory': {'spot_unscaled_accounts':36, 'spot_breakdown':'baseline + 3 mechanisms + cash + 4 protected participation controls, each all 4 stresses', 'coin_unscaled_accounts':16, 'coin_breakdown':'baseline + 3 mechanisms, each all 4 stresses', 'actual_calibrated_base_accounts_per_project':4, 'coin_incumbent_offset_base_diagnostics_seconds':[-60,60], 'fixed_budget_accounts':'three budgets per repo for baseline, three for selected only if different', 'applicable_combination':'four stresses plus actual calibrated base; no automatic one-component duplicate'},
}
spot = [
 {'name':'exit-confirm','order':1,'scope':'ordinary SMA exit only','rule':'delay only when latest completed close <= its current SMA AND immediately preceding completed close <= its own contemporaneous SMA; equality counts below', 'missing':'missing history cannot justify delay', 'preserve':['repair','adverse','overextended','protection exits','fresh entry','ATR stop'], 'held_topup_rebalance':False},
 {'name':'stop-budget','order':2,'scope':'genuine NEW BUY only', 'account_risk_fraction':'.12', 'risk':'proposed initial stop loss + cash fee reserves + sum(max(0, current_price - confirmed allocated protection stop) * owned_qty) of all existing owned sleeves <= .12 * current whole-account marked USDT equity', 'proof':'proven ownership and allocated stops required; missing ownership/protection blocks new risk', 'distance':'actual proposal entry/stop with original fee/slip assumptions', 'spend':'min(original proposal/free cash/90% pool/capital gates, remaining risk / distance); never increase original proposal', 'held_topup_rebalance':False, 'disclosure':'risk budget, not protection against gaps'},
 {'name':'crowding-interaction','order':3,'scope':'genuine NEW BUY only', 'funding_gt':'.0003', 'basis_gt':'.01', 'weak_momentum':'current completed daily close <= close five completed days earlier', 'rule':'halve original allowed spend only if all three conditions; otherwise preserve original proposal, including strong momentum', 'missing':'missing/stale funding/basis or causal history blocks new BUY only; safety exits remain', 'held_topup_rebalance':False},
]
coin = [
 {'name':'quality-budget','order':1,'scope':'primary new entry only; macro unchanged', 'full_quality':'current completed 4h close > mean(last 20 completed 4h closes) AND current close > close six bars earlier AND observed decision mark >= trigger completed close - .5 * trigger prior ATR14', 'fraction_if_full':'1','fraction_otherwise':'.5', 'missing':'missing causal trigger/history blocks primary new risk', 'preserve':'original committed entry/topup target and installed protection'},
 {'name':'cost-horizon','order':2,'scope':'owned longs; conditional cost exit includes macro, extension primary only', 'exit':'at actual legal session decision only, completed 4h close <= close six bars earlier AND latest known settled funding > .0003', 'missing_exit':'missing funding leaves original hold unchanged and is journaled', 'extension':'at actual session decision, primary owned opportunity age >=5 days and <7 days, current completed 4h close > mean(last 20 completed closes) AND current close > close six bars earlier AND known funding <= .0003', 'age_reference':'original trigger timestamp', 'original_expiry_days':7,'extended_expiry_days':10,'max_durable_extensions':1, 'preserve':'original stop/take and safety gates', 'prohibited':'no retroactive catch-up/history extension, no actions while stopped; macro has no primary lifetime'},
 {'name':'crowding-interaction','order':3,'scope':'primary new entry only; macro unchanged', 'funding_gt':'.0003','basis_gt':'.01','weak_momentum':'current completed 4h close <= close six bars earlier', 'rule':'halve primary original new-entry fraction only if all three conditions; otherwise unchanged', 'missing':'missing/stale features or causal history blocks primary new risk; exits remain available', 'evaluation':'independent of quality-budget and cost-horizon'},
]
for kind,repo,baseline,candidates,stresses,target,mdd in [
 ('spot','spotquant','atr-stop',spot,['base','fee150','slip2','outage'],{'cagr_min':'1','continuous_mdd_max':'.30'},'every continuous proxy MDD <= corresponding baseline'),
 ('coin','coinquant','incumbent',coin,['base','fees-x1.5','read-400ms','trigger-slip'],{'cagr_min':'1.50','continuous_mdd_strict_max':'.50'},'every continuous MDD < .50')]:
 spec={**shared,'project_kind':kind,'baseline_candidate':baseline,'default_sizing_scale':'1','candidate_order':[c['name'] for c in candidates],'candidates':candidates,'stresses':stresses,'targets':target,'scenario_mdd_gate':mdd,'compatibility':{'all_registered_mechanisms_compatible':True,'scope':'exit changes + new risk sizing; size factors compose without enlarging original proposal; safety priority remains','combine':'all eligible in registered order'}, 'account':({'long_cash':True,'leverage':False,'borrow':False} if kind=='spot' else {'one_way':True,'isolated':True,'default_shorts':False,'primary_risk':'7.5','macro_risk':'3.6'})}
 Path(f'/workspace/btc-alpha-beta-improve/{repo}/research/edge_spec.json').write_text(json.dumps(spec,indent=2,sort_keys=True)+'\n')
 protocol=f'''# Frozen BTC alpha/beta edge protocol — {kind}

Registered 2026-10-03 before new financial outcomes. The machine-readable contract is `edge_spec.json`; it is the finite registration, not a parameter search. Project `{kind}` baseline `{baseline}` remains scale1. No results or promotion are claimed here. Native qualification remains NOT_QUALIFIED and actual account-days zero.

## Economics and execution

BTCUSDT; initial CNY10000/no additions; 2020-01-01T00:00:00Z through 2026-09-20T00:00:00Z exclusive; original795 starts,300-second sessions/5-second polls, original FX/conversion/cost/latency/protection/ownership gates; stopped clients take no actions. Spot long/cash/no leverage; Coin one-way isolated/default no shorts, primary7.5/macro3.6. Goals Spot CAGR>=100%/continuous MDD<=30%, Coin>=150%/continuous MDD<50%. Native qualification remains NOT_QUALIFIED/actual account-days zero. Current Spot ATR scale1 and Coin incumbent are controls.

## Registered mechanisms, exact order

'''
 for candidate in candidates:
  protocol+=f"### {candidate['order']}. {candidate['name']}\n\n"
  protocol+='; '.join(f'{k}: {v}' for k,v in candidate.items() if k not in ['name','order'])+'.\n\n'
 protocol+='''All three mechanisms are compatible at their distinct decision scopes. Combine every individually eligible mechanism in registered order, with all sizing caps preserved; do not search subsets. Simple funding OR basis entry filters were prior failed research, not new hypotheses. Task1's verified Spot flat-day attribution supports testing ordinary-exit confirmation. Coin first divergence includes different observed marks and consequent sizing/rounding; no precise unnecessary same-observation dependency was established. No automatic phase fix or selected winning schedule offset is registered. Macro raw IDs remain actual negative creation timestamps; diagnostic association is not operating equality.

## Verified point-in-time feature inputs

The registered raw crowding SHA-256 is `1d87be0b4c8cd8a7eacd4970a1a194e5f1ed0b2f3aa3710a43417aa9ab066ef2`, 7488 funding and 2485 basis records. Reuse the controller's `research.prepare_inputs.build` reconstruction from official caches, independently compare both raw byte hashes, then recheck official archive CHECKSUMs, sizes, warmup and aggregate spot identities. Never accept copied metadata in place of verified bytes. The immutable reconstruction is outside the repositories; absent identity mismatch do not repeat full market reconstruction.

`edge-features-v1` contains funding/basis `{observation_ms, available_ms, value}` records, `source` raw and market hashes plus availability assumptions, and real `coverage`. Decimal values are strings; explicit missing values use null plus a nonempty cause. Content SHA-256 covers canonical JSON excluding its own field; file SHA-256 may be separately pinned by `FeatureBook(path, expected_sha256=...)`. These hashes bind content/provenance; they are not signatures. Each standalone repository supplies the same validated reader without a sibling runtime import or adapter requests.

Funding observation is the actual historical settlement stamp including jitter; availability is observation+28800000ms. Select only the latest record whose availability <= now. It is stale at age >=28800000ms since availability, exactly, with no repair/tolerance; negative rates remain negative. Predicted rates and future cashflows cannot become earlier features.

Basis observation is the previous matched UTC-day completion boundary, exactly raw available_ms-60000; retain raw stamps. The raw basis was previous daily futures trade close/spot trade close-1 at day-open+DAY+60000. Publication 60000ms after completion is a modeled assumption, not observed exchange publication. Require max age1DAY and the current UTC availability date. This is a trade-close proxy, not instantaneous executable basis. Before availability, during gaps, on stale/date mismatch, or outside the frozen historical window, return None with a specific journal cause. The complete raw tail remains preserved for identity but cannot extend historical lookup beyond the exclusive endpoint. Forward observations require a separate collection/artifact, never historical backfill. Completed trend bars remain in each project's causal model/trigger history; this module produces only the public funding/basis inputs, not a replacement bar history.

Spot builder: `python3.13 -m research.edge_features --build --crowding PATH --verified-crowding VERIFIED_PATH --perp-repo REPO --perp-market PATH --spot-market PATH --out NEW_PATH`. Defaults use sibling Coin only for verification of official warmup bytes and the official `/tmp` caches; the reader itself is standalone. Output creation is exclusive and existing outputs reject. Readers validate JSON uniqueness, file/content/raw/market identities, format, finite Decimal values, strict unique sorted observation/availability stamps, exact lag, UTC basis boundaries and recomputed frozen-window coverage. `last_lookup` optionally journals selected observation, availability, age, missing cause and hashes. No native requests or financial replay are involved.

## Controls, stresses and baseline equality

Cash plus protected-participation-25/50/75/100 use actual funded accounts, same finite session/Lifecycle, installed28% protective stop, no held topup/rebalance, genuine cold-start gates and next completed day after actual stop before re-entry. Their different signal/protection rules must be disclosed; they are not pure buy-and-hold or constant weights. No fractional daily-open curve is claimed executable.

Spot base/fee150/slip2/outage; Coin base/fees-x1.5/read-400ms/trigger-slip. All registered single mechanisms run all four stresses even if base loses. Spot baseline+3 mechanisms+5 controls produces36 unscaled accounts; Coin baseline+3 mechanisms produces16. Actual calibrated base reruns include baseline+3 candidates per project. Coin incumbent ±60s base accounts are diagnostics only. Applicable combinations run all four stresses and actual calibrated base. Accepted baseline replay must match all six original evidence groups under existing allowed normalization; unexplained mismatch blocks promotion. New envelopes bind exact sources without changing old raw fields to manufacture equality. Original Spot canonical meter and Coin incumbent no-op hooks may establish equality.

## Risk and adoption

Risk calibration uses only2020–2021 USDT731days. Scale=max(.01,min(1,baseline train vol/candidate train vol,baseline positive beta/candidate positive beta when candidate beta exceeds baseline)). Use scale1 before2022. Actual new order sizing only after cutoff1640995200000; no retroactive held shrink or curve scaling. Each project writes its OWN calibration document with own candidate-keyed profiles, binding project kind, baseline, spec/source/input identities. Rerun baseline scale1 and each candidate actual base. Achieved validation upper bands require vol<=baseline1.05 AND beta<=baseline+.02; this is not exact risk equality. All historical data are contaminated; regression intercepts/CIs remain descriptive.

Promotion requires complete/known/audited original matched stresses; every scenario CAGR>=baseline-.01; Spot every continuous proxy MDD<=corresponding baseline, Coin every MDD<.50. Base CAGR>=baseline+.01 OR base MDD<=baseline-.01 with CAGR>=baseline-.01. Base worst CNYday>=baseline-.005, historical ES99 loss<=baseline1.05 and longest underwater no longer than baseline. Both actual risk upper bands must pass. Return-increasing promotion additionally requires validation cumulativeUSDTreturn gain>0; risk-only alternative requires continuousMDD reduction>=.01 with validation gain>=-.01. Rank highest worst-stressCAGR then registered candidate order. Original targets separately stay NOT_MET unless exact goals pass. Retain each original producer year convention. Combine all individually eligible compatible mechanisms with no subset search, remeasure all four stresses and actual calibrated base, adopt only the combination's own gates pass.

## Fixed two-account capital

Actual fixed Spot/Coin CNY2500/7500,5000/5000,7500/2500 accounts for current defaults and final selected if different; no added cash, transfers or rebalance. Sum actual synchronized daily equity curves and closing BTC exposure. Daily joint MDD is not continuous joint MDD. 5000/5000 is the predeclared neutral reference; other splits are sensitivity evidence, not an optimized default.

## Verification and limits

Meaningful offline tests cover before/at availability, exact eight-hour expiry, settlement jitter, missing/current-date/stale basis, invalid/duplicate/nonfinite records, future-tail perturbation invariance, negative funding and identical standalone readers in both repos. Source identities and real coverage are emitted to external task-artifacts without modifying old evidence. All Coin tests/producers sharing UIDs remain strictly serial; HOME/locks are unchanged. Clean committed source/spec/input identities freeze before new financial measurements. Unit tests and public historical proxies do not prove financial success, prospective alpha, native execution or qualification.
'''
 Path(f'/workspace/btc-alpha-beta-improve/{repo}/research/edge-PROTOCOL.md').write_text(protocol)
